#!/usr/bin/env node
/*
 * build-content.js — bake content.json into the pages.
 *
 *   node build-content.js          # bake tokens into every .html file
 *   node build-content.js --check  # fail if any page is out of date
 *
 * Why this exists
 * ---------------
 * The pages reference shared values as {{tokens}} so that prices, caps and
 * counts live in exactly one place (content.json). Substituting them at
 * runtime with fetch() works over HTTP but fails on file://, where the
 * browser blocks the request — leaving visible {{tokens}} in the copy.
 *
 * So tokens are substituted at build time instead, into an inline map that
 * site.js prefers over the network. The pages then render correctly whether
 * they are opened from disk, served locally, or deployed.
 *
 * content.json remains the single source of truth. After editing it, run
 * this script and commit the result.
 */

"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const CONTENT = path.join(ROOT, "content.json");
const CHECK = process.argv.includes("--check");

const TIER_ORDER = ["basic", "stream", "gaming"];

function buildMap(content) {
  const map = {
    "network.countries": content.network.countries,
    "network.cities": content.network.cities,
    "network.servers": content.network.servers,
    "network.uptime": content.network.uptime,
    "policy.refundDays": content.policy.refundDays,
    "policy.graceDays": content.policy.graceDays,
    "policy.auditCadence": content.policy.auditCadence,
    "brand.company": content.brand.company,
    "brand.jurisdiction": content.brand.jurisdiction,
    "brand.domain": content.brand.domain
  };

  TIER_ORDER.forEach((key) => {
    const t = content.tiers[key];
    map["tiers." + key + ".name"] = t.name;
    map["tiers." + key + ".price"] = t.price;
    map["tiers." + key + ".annual"] = t.annual;
    map["tiers." + key + ".annualTotal"] = t.annualTotal;
    map["tiers." + key + ".cap"] = t.cap;
    map["tiers." + key + ".devices"] = t.devices;
    map["tiers." + key + ".tagline"] = t.tagline;
  });

  return map;
}

/* The inline block site.js reads before it tries the network.
   This is the full content.json object (not the flattened token map), so the
   interactive code — tier switching, the billing toggle, the signup summary —
   has the same structured data it would get from fetching content.json. */
function inlineScript(content) {
  return (
    "<script>\n" +
    "  /* Generated by build-content.js from content.json — do not edit by hand.\n" +
    "     Inlined so the pages render and behave correctly from file:// as well\n" +
    "     as over HTTP, where fetch() is available. */\n" +
    "  window.LOCUS_CONTENT = " + JSON.stringify(content) + ";\n" +
    "</script>"
  );
}

const MARKER_START = "<!-- LOCUS_CONTENT_START -->";
const MARKER_END = "<!-- LOCUS_CONTENT_END -->";

/* Substitute every {{token}} in the markup itself, so the page is correct
   with no JavaScript at all. Text nodes and attribute values are both
   handled, which covers copy, <title>, meta descriptions and hrefs. */
function substitute(html, map) {
  return html.replace(/\{\{([\w.]+)\}\}/g, function (match, key) {
    const value = map[key];
    return value === undefined ? match : value;
  });
}

function bake(html, map, content) {
  const block = MARKER_START + "\n" + inlineScript(content) + "\n" + MARKER_END;

  const existing = new RegExp(
    MARKER_START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") +
      "[\\s\\S]*?" +
      MARKER_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  );

  let out;

  if (existing.test(html)) {
    // Re-bake: restore the block, then substitute the rest of the document.
    out = html.replace(existing, block);
  } else {
    // First run: insert the block just before the first components.js script.
    const anchor = html.indexOf('<script src="components.js">');
    if (anchor === -1) return html;

    const before = html.slice(0, anchor);
    const after = html.slice(anchor);
    const indent = (before.match(/\n([ \t]*)$/) || ["", ""])[1] || "";
    const indented = block
      .split("\n")
      .map((line) => (line ? indent + line : line))
      .join("\n");

    out = before + indented + "\n" + after;
  }

  return substitute(out, map);
}

function main() {
  if (!fs.existsSync(CONTENT)) {
    console.error("content.json not found");
    process.exit(1);
  }

  let content;
  try {
    content = JSON.parse(fs.readFileSync(CONTENT, "utf8"));
  } catch (err) {
    console.error("content.json is not valid JSON:", err.message);
    process.exit(1);
  }

  const map = buildMap(content);
  const files = fs.readdirSync(ROOT).filter((f) => f.endsWith(".html")).sort();

  let changed = 0;
  let stale = 0;

  for (const file of files) {
    const full = path.join(ROOT, file);
    const original = fs.readFileSync(full, "utf8");
    const baked = bake(original, map, content);

    if (baked === original) continue;

    if (CHECK) {
      console.log("  out of date: " + file);
      stale++;
      continue;
    }

    fs.writeFileSync(full, baked);
    console.log("  baked: " + file);
    changed++;
  }

  if (CHECK) {
    if (stale) {
      console.error(
        "\n" + stale + " page(s) out of date. Run: node build-content.js"
      );
      process.exit(1);
    }
    console.log("all pages up to date with content.json");
    return;
  }

  console.log(
    changed
      ? "\n" + changed + " page(s) updated from content.json"
      : "all pages already up to date"
  );
}

main();
