#!/usr/bin/env bash
# Module 05: Caddy Reverse Proxy
# Installs Caddy with the caddy-ratelimit plugin and deploys Caddyfile with:
#   - TLS via Let's Encrypt
#   - Rate limiting zones (fingerprint-keyed for activation)
#   - Reverse proxy to PocketBase (127.0.0.1:8090)
#   - Static file serving for update.json
#
# Installation strategy:
#  1. Install base Caddy from official APT repo (for systemd integration)
#  2. Check if rate_limit module exists
#  3. If missing, build custom Caddy with xcaddy (adds caddy-ratelimit plugin)
#  4. Replace the binary with the custom build
set -euo pipefail

log()  { echo "[05-caddy] $*"; }
warn() { echo "[05-caddy][WARN] $*"; }
fail() { echo "[05-caddy][FAIL] $*"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$(dirname "$SCRIPT_DIR")/templates"
CADDYFILE="/etc/caddy/Caddyfile"
CADDY_DATA_DIR="/var/www/html"

: "${DOMAIN:?DOMAIN is required}"

# ── Install or rebuild Caddy with rate_limit support ──
install_caddy() {
    # Check if Caddy already has rate_limit
    if command -v caddy &>/dev/null; then
        local ver
        ver=$(caddy version 2>/dev/null | head -1 | cut -d' ' -f1 || echo "unknown")
        log "Caddy already installed (v${ver})"
        if caddy list-modules 2>/dev/null | grep -q "http.handlers.rate_limit"; then
            log "✓ rate_limit module present"
            return 0
        fi
        log "rate_limit module missing. Will download custom build..."
    else
        log "Caddy not found. Will download custom build with rate_limit..."
    fi

    # Download pre-built Caddy with ratelimit plugin from official API
    # This is MUCH faster than building from source with xcaddy
    log "Downloading Caddy with ratelimit plugin from caddyserver.com..."

    local tmpfile
    tmpfile=$(mktemp /tmp/caddy-XXXXXX)

    if ! curl -sL 'https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com/mholt/caddy-ratelimit' \
        -o "$tmpfile"; then
        rm -f "$tmpfile"
        fail "Failed to download Caddy with ratelimit plugin"
    fi

    # Verify it's a valid binary
    if ! file "$tmpfile" | grep -q "ELF"; then
        rm -f "$tmpfile"
        fail "Downloaded file is not a valid ELF binary"
    fi

    chmod +x "$tmpfile"
    local ver
    ver=$("$tmpfile" version 2>/dev/null | head -1 || echo "unknown")
    log "Downloaded Caddy ${ver}"

    # Verify ratelimit module is included
    if ! "$tmpfile" list-modules 2>/dev/null | grep -q "http.handlers.rate_limit"; then
        rm -f "$tmpfile"
        fail "Downloaded Caddy does not include rate_limit module"
    fi
    log "✓ rate_limit module confirmed in downloaded binary"

    # Replace the installed Caddy binary
    systemctl stop caddy 2>/dev/null || true
    cp "$tmpfile" /usr/bin/caddy
    chmod +x /usr/bin/caddy
    rm -f "$tmpfile"

    log "✓ Caddy replaced with ratelimit-enabled version: $(caddy version | head -1)"
}

# ── Deploy Caddyfile ──
deploy_caddyfile() {
    mkdir -p /etc/caddy "$CADDY_DATA_DIR"

    cat > "$CADDYFILE" << CADDY
# MyVPN Caddyfile — generated by modular setup
# Domain: ${DOMAIN}

{
    # rate_limit is configured per-handle below
}

# ── Main site block ──
${DOMAIN} {
    root * ${CADDY_DATA_DIR}
    file_server

    # ── Security headers ──
    header {
        -Server
        X-Content-Type-Options "nosniff"
        X-Frame-Options "DENY"
        Referrer-Policy "no-referrer"
        Permissions-Policy "geolocation=(), microphone=(), camera=()"
    }

    # ── Activation endpoint (rate limited: 5 per 10 min per IP) ──
    handle /api/activate {
        rate_limit {
            zone activation {
                key {remote_host}
                events 5
                window 10m
            }
        }
        reverse_proxy 127.0.0.1:8090
    }

    # ── Heartbeat endpoint (rate limited: 1 per 10s per IP) ──
    handle /api/heartbeat {
        rate_limit {
            zone heartbeat {
                key {remote_host}
                events 1
                window 10s
            }
        }
        reverse_proxy 127.0.0.1:8090
    }

    # ── General API (rate limited: 100 per 10s per IP) ──
    handle /api/* {
        rate_limit {
            zone api_default {
                key {remote_host}
                events 100
                window 10s
            }
        }
        reverse_proxy 127.0.0.1:8090
    }

    # ── PocketBase admin UI (no rate limit) ──
    handle /_/* {
        reverse_proxy 127.0.0.1:8090
    }

    # ── Static files ──
    handle /update.json {
        file_server
    }

    # ── Logging ──
    log {
        output file /var/log/caddy/access.log
        format json
    }

    # ── TLS via Let's Encrypt ──
    tls {
        protocols tls1.2 tls1.3
        curves x25519 secp384r1
    }
}
CADDY
    log "✓ Caddyfile deployed to ${CADDYFILE}"
}

# ── Create update.json placeholder ──
deploy_update_json() {
    local update_file="${CADDY_DATA_DIR}/update.json"
    # Only write if missing or version changed
    if [ ! -f "$update_file" ]; then
        cat > "$update_file" <<'EOF'
{
  "version": "1.0.0",
  "rollout_percent": 0,
  "linux_amd64": null,
  "windows": null,
  "macos_intel": null,
  "macos_arm": null
}
EOF
        log "✓ Created placeholder update.json"
    else
        log "update.json already exists"
    fi
    chmod 644 "$update_file"
}

# ── Create systemd service (if not installed via APT) ──
create_systemd_service() {
    local service_file="/etc/systemd/system/caddy.service"
    if [ -f "$service_file" ]; then
        log "Caddy systemd service already exists"
        return 0
    fi

    # Create caddy user if not exists
    if ! id -u caddy &>/dev/null; then
        useradd --system --no-create-home --shell /usr/sbin/nologin caddy 2>/dev/null || true
    fi

    mkdir -p /var/lib/caddy /var/log/caddy /var/www/html /etc/caddy
    chown -R caddy:caddy /var/lib/caddy /var/log/caddy /var/www/html
    chmod 755 /var/www/html

    cat > "$service_file" << 'SERVICE'
[Unit]
Description=Caddy Web Server
Documentation=https://caddyserver.com/docs/
After=network.target network-online.target
Requires=network-online.target

[Service]
Type=notify
User=caddy
Group=caddy
ExecStart=/usr/bin/caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
Environment=XDG_CONFIG_HOME=/var/lib/caddy
Environment=XDG_DATA_HOME=/var/lib/caddy

[Install]
WantedBy=multi-user.target
SERVICE
    log "✓ Created systemd service: ${service_file}"

    # Grant capability to bind to low ports (<1024) as non-root
    setcap cap_net_bind_service=+ep /usr/bin/caddy 2>/dev/null && \
        log "✓ Granted cap_net_bind_service to caddy binary" || \
        warn "Could not set cap_net_bind_service (Caddy will need root to bind :80/:443)"
}

# ═══════════════════════════════════════════
# Main
# ═══════════════════════════════════════════

install_caddy
create_systemd_service
deploy_caddyfile
deploy_update_json

# ── Enable and start Caddy ──
systemctl daemon-reload
systemctl enable caddy 2>/dev/null || true
systemctl restart caddy 2>&1 | tail -5 || {
    warn "Caddy restart failed. Checking config..."
    caddy validate --config "$CADDYFILE" 2>&1 | tail -5 || true
    journalctl -u caddy -n 10 --no-pager 2>&1 | tail -5 || true
}

# ── Verify ──
sleep 2
if systemctl is-active --quiet caddy; then
    log "✓ Caddy is running"
    log "  Caddy version: $(caddy version 2>/dev/null | head -1)"
    if caddy list-modules 2>/dev/null | grep -q "http.handlers.rate_limit"; then
        log "✓ rate_limit module confirmed active"
    fi
else
    warn "Caddy may not be running. Check: journalctl -u caddy -n 20 --no-pager"
    warn "  Config: ${CADDYFILE}"
    warn "  Test: caddy validate --config ${CADDYFILE}"
fi

log "✓ Caddy setup complete"
exit 0
