#!/usr/bin/env bash
# Module 05: Caddy Reverse Proxy
# Installs Caddy with the caddy-ratelimit plugin and deploys Caddyfile with:
#   - TLS via Let's Encrypt
#   - Rate limiting zones (fingerprint-keyed for activation)
#   - Reverse proxy to PocketBase (127.0.0.1:8090)
#   - Static file serving for update.json
#
# Installation strategy:
#  1. Install base Caddy from official APT repo (for systemd integration)
#  2. Check if rate_limit module exists
#  3. If missing, build custom Caddy with xcaddy (adds caddy-ratelimit plugin)
#  4. Replace the binary with the custom build
set -euo pipefail

log()  { echo "[05-caddy] $*"; }
warn() { echo "[05-caddy][WARN] $*"; }
fail() { echo "[05-caddy][FAIL] $*"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$(dirname "$SCRIPT_DIR")/templates"
CADDYFILE="/etc/caddy/Caddyfile"
CADDY_DATA_DIR="/var/www/html"

: "${DOMAIN:?DOMAIN is required}"

# ── Install or rebuild Caddy with rate_limit support ──
install_caddy() {
    # Check if Caddy already has rate_limit
    if command -v caddy &>/dev/null; then
        local ver
        ver=$(caddy version 2>/dev/null | head -1 | cut -d' ' -f1 || echo "unknown")
        log "Caddy already installed (v${ver})"
        if caddy list-modules 2>/dev/null | grep -q "http.handlers.rate_limit"; then
            log "✓ rate_limit module present"
            return 0
        fi
        log "rate_limit module missing. Will download custom build..."
    else
        log "Caddy not found. Will download custom build with rate_limit..."
    fi

    # Download pre-built Caddy with ratelimit plugin from official API
    # This is MUCH faster than building from source with xcaddy
    log "Downloading Caddy with ratelimit plugin from caddyserver.com..."

    local tmpfile
    tmpfile=$(mktemp /tmp/caddy-XXXXXX)

    if ! curl -sL 'https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com/mholt/caddy-ratelimit' \
        -o "$tmpfile"; then
        rm -f "$tmpfile"
        fail "Failed to download Caddy with ratelimit plugin"
    fi

    # Verify it's a valid binary
    if ! file "$tmpfile" | grep -q "ELF"; then
        rm -f "$tmpfile"
        fail "Downloaded file is not a valid ELF binary"
    fi

    chmod +x "$tmpfile"
    local ver
    ver=$("$tmpfile" version 2>/dev/null | head -1 || echo "unknown")
    log "Downloaded Caddy ${ver}"

    # Verify ratelimit module is included
    if ! "$tmpfile" list-modules 2>/dev/null | grep -q "http.handlers.rate_limit"; then
        rm -f "$tmpfile"
        fail "Downloaded Caddy does not include rate_limit module"
    fi
    log "✓ rate_limit module confirmed in downloaded binary"

    # Replace the installed Caddy binary
    systemctl stop caddy 2>/dev/null || true
    cp "$tmpfile" /usr/bin/caddy
    chmod +x /usr/bin/caddy
    rm -f "$tmpfile"

    log "✓ Caddy replaced with ratelimit-enabled version: $(caddy version | head -1)"
}

# ── Deploy Caddyfile ──
deploy_caddyfile() {
    mkdir -p /etc/caddy "$CADDY_DATA_DIR"

    cat > "$CADDYFILE" << CADDY
# MyVPN Caddyfile — generated by modular setup
# Domain: ${DOMAIN}

{
    # Change directive ordering: rate_limit after basic_auth
    order rate_limit after basic_auth
}

# ── Main site block ──
${DOMAIN} {
    root * ${CADDY_DATA_DIR}
    file_server

    # ── Security headers ──
    header {
        -Server
        X-Content-Type-Options "nosniff"
        X-Frame-Options "DENY"
        Referrer-Policy "no-referrer"
        Permissions-Policy "geolocation=(), microphone=(), camera=()"
    }

    # ── Rate limiting (site-level, applies to all routes below) ──
    # Activation zone: 5 attempts per 10 min per fingerprint/IP
    # Heartbeat zone: 1 request per 10s per IP
    # Default zone: 100 requests per 10s per IP
    # Rate limiting — each zone has a single key
    # Activation: rate-limited by client IP (5 attempts per 10 min)
    # Heartbeat: rate-limited by client IP (1 per 10s)
    # Default: rate-limited by client IP (100 per 10s)
    rate_limit {
        zone activation_zone {
            key {remote_host}
            events 5
            window 10m
        }
        zone heartbeat_zone {
            key {remote_host}
            events 1
            window 10s
        }
        zone default {
            key {remote_host}
            events 100
            window 10s
        }
    }

    # ── Main API reverse proxy (includes activation endpoint) ──
    handle /api/* {
        reverse_proxy 127.0.0.1:8090
    }

    # ── Heartbeat endpoint ──
    handle /api/heartbeat {
        reverse_proxy 127.0.0.1:8090
    }

    # ── PocketBase admin UI ──
    handle /_/* {
        reverse_proxy 127.0.0.1:8090
    }

    # ── Static files ──
    handle /update.json {
        file_server
    }

    # ── Logging ──
    log {
        output file /var/log/caddy/access.log
        format json
    }

    # ── TLS via Let's Encrypt ──
    tls {
        protocols tls1.2 tls1.3
        curves x25519 secp384r1
    }
}
CADDY
    log "✓ Caddyfile deployed to ${CADDYFILE}"
}

# ── Create update.json placeholder ──
deploy_update_json() {
    local update_file="${CADDY_DATA_DIR}/update.json"
    if [ ! -f "$update_file" ]; then
        cat > "$update_file" <<'EOF'
{
  "version": "1.0.0",
  "rollout_percent": 0,
  "windows": null,
  "macos_intel": null,
  "macos_arm": null
}
EOF
        log "✓ Created placeholder update.json"
    else
        log "update.json already exists"
    fi
    chmod 644 "$update_file"
}

# ═══════════════════════════════════════════
# Main
# ═══════════════════════════════════════════

install_caddy
deploy_caddyfile
deploy_update_json

# ── Enable and start Caddy ──
systemctl enable caddy 2>/dev/null || true
systemctl restart caddy 2>&1 | tail -5 || {
    warn "Caddy restart failed. Checking config..."
    caddy validate --config "$CADDYFILE" 2>&1 | tail -5 || true
    journalctl -u caddy -n 10 --no-pager 2>&1 | tail -5 || true
}

# ── Verify ──
sleep 2
if systemctl is-active --quiet caddy; then
    log "✓ Caddy is running"
    log "  Caddy version: $(caddy version 2>/dev/null | head -1)"
    if caddy list-modules 2>/dev/null | grep -q "http.handlers.rate_limit"; then
        log "✓ rate_limit module confirmed active"
    fi
else
    warn "Caddy may not be running. Check: journalctl -u caddy -n 20 --no-pager"
    warn "  Config: ${CADDYFILE}"
    warn "  Test: caddy validate --config ${CADDYFILE}"
fi

log "✓ Caddy setup complete"
exit 0
