package winres

import (
	"os"
	"path/filepath"
	"testing"
)

// repoVersion reads the canonical version from v5/VERSION.
// Path: v5/client/internal/winres -> ../../../VERSION
func repoVersion(t *testing.T) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "VERSION"))
	if err != nil {
		t.Fatalf("cannot read v5/VERSION: %v", err)
	}
	v := string(trimSpace(data))
	if v == "" {
		t.Fatal("v5/VERSION is empty")
	}
	return v
}

func trimSpace(b []byte) []byte {
	start, end := 0, len(b)
	for start < end && (b[start] == ' ' || b[start] == '\n' || b[start] == '\r' || b[start] == '\t') {
		start++
	}
	for end > start && (b[end-1] == ' ' || b[end-1] == '\n' || b[end-1] == '\r' || b[end-1] == '\t') {
		end--
	}
	return b[start:end]
}

// TestCommittedSysoMatchesRepoVersion is the guard that would have caught the
// shipped defect. The committed rsrc_windows_*.syso files stamped version 2.0.0
// and product name "MyVPN" while v5/VERSION said 2.1.0 and the app had been
// renamed to Locus. The previous guard only grepped main.go's go:generate
// DIRECTIVE for the right number — and the directive was right. The artifacts
// are what shipped, and nothing looked at them.
//
// This runs natively on any platform because it reads the file as bytes; it
// does not need a Windows toolchain.
func TestCommittedSysoMatchesRepoVersion(t *testing.T) {
	want := repoVersion(t)

	for _, arch := range []string{"amd64", "arm64"} {
		t.Run(arch, func(t *testing.T) {
			path := filepath.Join("..", "..", "rsrc_windows_"+arch+".syso")
			if _, err := os.Stat(path); err != nil {
				t.Skipf("%s not present — regenerate with: cd v5/client && go generate -tags windows", path)
			}

			v, ok, err := ReadFile(path)
			if err != nil {
				t.Fatalf("reading %s: %v", path, err)
			}
			if !ok {
				t.Fatalf("no VS_VERSION_INFO strings found in %s.\n"+
					"The resource format has changed and this guard is now BLIND. "+
					"Fix the parser — do not delete the check: a stale .syso ships a "+
					"Windows binary whose Properties tab reports the wrong version "+
					"and product name.", path)
			}

			if v.FileVersion != want {
				t.Errorf("%s FileVersion = %q, want %q (v5/VERSION).\n"+
					"Regenerate: cd v5/client && go generate -tags windows\n"+
					"A student right-clicking locus.exe would otherwise see a version "+
					"that does not exist.", path, v.FileVersion, want)
			}
			if v.ProductVersion != want {
				t.Errorf("%s ProductVersion = %q, want %q", path, v.ProductVersion, want)
			}
			if v.ProductName != "Locus" {
				t.Errorf("%s ProductName = %q, want %q — the old brand must not "+
					"survive in shipped executable metadata", path, v.ProductName, "Locus")
			}
			// FileDescription is what Windows shows as the primary label, so it
			// is the most visible of the four.
			if !hasPrefix(v.FileDesc, "Locus") {
				t.Errorf("%s FileDescription = %q, want it to start with %q",
					path, v.FileDesc, "Locus")
			}
		})
	}
}

func hasPrefix(s, prefix string) bool {
	return len(s) >= len(prefix) && s[:len(prefix)] == prefix
}

// TestParseFindsBothAlignments pins the decoder against a synthetic block, so a
// regression in the offset handling is caught even if the real .syso files are
// regenerated by a tool that changes alignment.
func TestParseFindsBothAlignments(t *testing.T) {
	// "FileVersion" / "9.9.9" / "ProductName" / "Locus", then a length-matched
	// pad so the second alignment is exercised too.
	encode := func(s string) []byte {
		out := make([]byte, 0, len(s)*2+2)
		for _, r := range s {
			out = append(out, byte(r), 0)
		}
		return append(out, 0, 0)
	}
	var blob []byte
	for _, s := range []string{"FileVersion", "9.9.9", "ProductName", "Locus"} {
		blob = append(blob, encode(s)...)
	}

	v, ok, err := Parse(blob)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if !ok {
		t.Fatal("Parse found nothing in a synthetic block that definitely contains the keys")
	}
	if v.FileVersion != "9.9.9" {
		t.Errorf("FileVersion = %q, want 9.9.9", v.FileVersion)
	}
	if v.ProductName != "Locus" {
		t.Errorf("ProductName = %q, want Locus", v.ProductName)
	}
}

// TestParseReportsNothingForGarbage guards the "blind guard" contract: a file
// the parser cannot understand must report ok=false so callers fail loudly
// rather than silently passing.
func TestParseReportsNothingForGarbage(t *testing.T) {
	_, ok, err := Parse([]byte{0x00, 0x01, 0x02, 0x03, 0xff, 0xfe})
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if ok {
		t.Error("Parse claimed to find version info in 6 bytes of noise — " +
			"the guard would silently pass on a corrupt resource")
	}
}
